# Generated by Django 3.1.2 on 2020-10-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_auto_20201011_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='items',
            field=models.ManyToManyField(to='prescription.Item'),
        ),
    ]
